Урок 7. Рефакторинг
LoC743/OnlineShopGB pull request #7
Opened 2021-07-11 17:37 UTC by LoC743

2021-07-16 11:26 UTC, LoC743 commented on OnlineShopGB/OnlineShopGB/App/BuisnessLogic/Network/Auth.swift
> +        self.baseUrl = URL(string: baseURL)!
Изменено в #9 [коммит](https://github.com/LoC743/OnlineShopGB/pull/9/commits/7722798ede8d8d0740474bc2f512976c4b5f0f6d)

2021-07-19 10:02 UTC, DrBoat requested changes
Прикольный под для логов.
Комментарий который я оставил относится ко всем таким местам (можешь сделать поиск восклицательного знака по проекту). 
Сделай все строчки по возможности до 120 символов. Например, переносом аргументов на новые строчки в объявлениях и вызовах функций.
На iPhone SE экран изменения данных некорректно работает. Нельзя пролистнуть вниз при показанной клавиатуре.

2021-07-19 10:02 UTC, vozleev commented on OnlineShopGB/OnlineShopGB/App/BuisnessLogic/Network/Cart.swift
> +        self.baseUrl = URL(string: baseURL + StringResources.cartAddURL)!
А это изменено? Если нет, то жду в следующих дз

2021-07-19 10:33 UTC, LoC743 commented on OnlineShopGB/OnlineShopGB/App/BuisnessLogic/Network/Cart.swift
> +        self.baseUrl = URL(string: baseURL + StringResources.cartAddURL)!
> А это изменено? Если нет, то жду в следующих дз

Да, url создаются теперь [тут](https://github.com/LoC743/OnlineShopGB/blob/feature/homework9/OnlineShopGB/OnlineShopGB/App/BuisnessLogic/Network/RequestFactory.swift)

2021-07-19 11:20 UTC, LoC743 commented
> Комментарий который я оставил относится ко всем таким местам (можешь сделать поиск восклицательного знака по проекту).

(Коммит с URL -> через guard)[https://github.com/LoC743/OnlineShopGB/pull/9/commits/7722798ede8d8d0740474bc2f512976c4b5f0f6d]
(В alert был textField -> guard)[https://github.com/LoC743/OnlineShopGB/pull/9/commits/bc591a7a9fc9d917236c8527b246d85c982e0079]

> Сделай все строчки по возможности до 120 символов. Например, переносом аргументов на новые строчки в объявлениях и вызовах функций.

В [этом коммите](https://github.com/LoC743/OnlineShopGB/pull/9/commits/534e631b470087887f0fb100ee485fea3d65f53c) прошелся по всему проекту и сделал переносы строк.

> На iPhone SE экран изменения данных некорректно работает. Нельзя пролистнуть вниз при показанной клавиатуре.

В [в этом коммите](https://github.com/LoC743/OnlineShopGB/pull/9/commits/35c83e884ebc002a37595f008ecee2ffe3a29f7e) добавил scrollView для экрана регистрации/изменения данных

2021-07-19 13:07 UTC, DrBoat approved these changes
Поставлю аппрув, а ты тогда в следующих дз все исправь, чтоб конфликтов не было

2021-07-22 15:35 UTC, merged